name: running my job for every 5 mins 
on:
  schedule:
    - cron : '*/5 * * * *'
    
jobs:
  test-schedule:
    runs-on: ubuntu-latest
    steps:
     - name: this is a cron job
       run: echo "this is my 1st job"
      
   
